name: Setup Nox
description: "Prepare and cache nox, install poetry."

inputs:
  poetry_version:
    description: "Which poetry version to use."
    required: True
    default: 1.3.0

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: "Install nox"
      run: pipx install nox
      shell: bash
    - uses: actions/cache@v3
      with:
        # nox & the poetry installation itself
        path: |
          .nox
          ~/.local
        key: nox-${{ github.job }}-${{ hashFiles('noxfile.py') }}-${{ hashFiles('poetry.lock') }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry_version }}
