name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  POETRY_VERSION: 1.3.0
  CACHE_NUMBER: 6

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nox and Poetry
        uses: ./.github/actions/setup_nox
        with:
          cache_number: ${{ env.CACHE_NUMBER }}
          poetry_version: ${{ env.POETRY_VERSION }}
      - name: Check for Dependency Vulnerabilities
        run: nox -s security

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nox and Poetry
        uses: ./.github/actions/setup_nox
        with:
          cache_number: ${{ env.CACHE_NUMBER }}
          poetry_version: ${{ env.POETRY_VERSION }}
      - name: Test Code and Docs
        run: nox -s tests
      - name: Upload to codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
